Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2019-12, with the labels that each got.

#118 Update screenshot in README
  README.md
Labels: 2: Dev Review

#113 GH-86: Notification in channel on MR reopen
  server/webhook/merge_request.go
  server/webhook/merge_request_test.go
Labels: 3: Reviews Complete

#122 [GH-74] Configuration change must propagate to client side
  server/api.go
Labels: 3: Reviews Complete

#125 [GH-65] Subgroups support
  go.mod
  go.sum
  server/command.go
  server/configuration.go
  server/gitlab/api.go
  server/gitlab/gitlab.go
  server/plugin.go
  server/subscriptions.go
  server/utils.go
  server/utils_test.go
  server/webhook.go
  server/webhook/issue.go
  server/webhook/issue_test.go
  server/webhook/merge_request.go
  server/webhook/merge_request_test.go
  server/webhook/note.go
  server/webhook/note_test.go
  server/webhook/pipeline.go
  server/webhook/pipeline_test.go
  server/webhook/push.go
  server/webhook/push_test.go
  server/webhook/tag.go
  server/webhook/tag_test.go
  server/webhook/webhook.go
  server/webhook/webhook_test.go
Labels: 2: QA Review
