Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2019-08, with the labels that each got.

#87 :bug: Fix bug : unsubscribe organization fail
  server/subscriptions.go
  server/subscriptions_test.go
Labels: 2: Dev Review

#84 Link to root URL with button
  webapp/src/components/sidebar_buttons/sidebar_buttons.jsx
Labels: 3: Reviews Complete

#82 List commits on push event
  server/webhook/push.go
  server/webhook/push_fixture_test.go
  server/webhook/push_test.go
Labels: 2: Dev Review

#81 [MM-17643] Make command responses post ephemeral messages at Gitlab bot user
  server/command.go
Labels: 3: Reviews Complete

#88 [MM-17037] Bump version to 1.0.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 1: PM Review

#85 Don't send event if there are no commits
  server/webhook/push.go
  server/webhook/push_fixture_test.go
  server/webhook/push_test.go
Labels: 3: Reviews Complete
