Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2021-09, with the labels that each got.

#220 Update environment.md
  docs/development/environment.md
  docs/setup/configuration.md
Labels: 4: Reviews Complete

#256 Update GitLab README.md
  README.md
Labels: 2: Dev Review

#260 fix the link to get the pending reviews
  webapp/src/components/sidebar_buttons/sidebar_buttons.jsx
Labels: 4: Reviews Complete, Docs/Not Needed

#255 MM-37922 - Add support for Chimera to GitLab plugin
  go.mod
  go.sum
  plugin.json
  server/configuration.go
  server/configuration_test.go
  server/plugin.go
Labels: 4: Reviews Complete
