Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2022-12, with the labels that each got.

#333 RHS Subscriptions
  .nvmrc
  public/app-bar-icon.png
  server/api.go
  server/api_test.go
  server/command.go
  server/command_test.go
  server/plugin.go
  webapp/package.json
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/client/client.js
  webapp/src/components/rhs_sidebar/index.js
  webapp/src/components/rhs_sidebar/mattermost_gitlab.jsx
  webapp/src/components/rhs_sidebar/no_subscriptions.jsx
  webapp/src/components/rhs_sidebar/rhs_sidebar.css
  webapp/src/components/rhs_sidebar/rhs_sidebar.jsx
  webapp/src/index.js
  webapp/src/reducers/index.js
  webapp/src/websocket/index.js
Labels: 4: Reviews Complete

#346 Set request context timeout to 30 seconds for plugin http endpoints
  server/api.go
Labels: 2: Dev Review, 3: QA Review

#350 Use for CI reusable workflows for DRY
  .circleci/config.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 2: Dev Review
