Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2022-11, with the labels that each got.

#302 Add support for triggering pipelines and job status updates
  CODEOWNERS
  server/command.go
  server/gitlab/api.go
  server/gitlab/gitlab.go
  server/gitlab/mocks/mock_gitlab.go
  server/gitlab/pipeline.go
  server/subscription/subscription.go
  server/webhook.go
  server/webhook/constants.go
  server/webhook/job_fixture_test.go
  server/webhook/jobs.go
  server/webhook/jobs_test.go
  server/webhook/webhook.go
  server/webhook/webhook_test.go
  server/webhook_test.go
Labels: 3: QA Review, Hacktoberfest

#334 Remove pipeline trigger subcommand from the autocomplete
  server/command.go
Labels: 2: Dev Review

#335 Add help documentation for pipeline run
  server/command.go
Labels: 2: Dev Review

#323 Fix error handling typo
  server/webhook.go
Labels: 4: Reviews Complete

#339 Release 1.5.2
  plugin.json
Labels: 4: Reviews Complete
