Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2023-01, with the labels that each got.

#353 Log non actionable errors on WARN level
  server/api.go
  server/cluster.go
  server/command.go
  server/plugin.go
  server/subscriptions.go
  server/webhook.go
Labels: 4: Reviews Complete

#347 Anchor the appsbar icon to SiteURL
  webapp/src/index.js
Labels: 3: QA Review

#355 Remove spurious message re: pipeline info
  server/command.go
Labels: 2: Dev Review, QA Review Done

#340 Release v1.6.0
  plugin.json
Labels: 4: Reviews Complete

#357 Point re-usable workflows to standard version
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 2: Dev Review
