Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2024-02, with the labels that each got.

#451 [MM-176] Sync the plugin with starter template
  .gitattributes
  .gitignore
  Makefile
  README.md
  build/legacy.mk
  build/manifest/main.go
  build/pluginctl/logs.go
  build/pluginctl/logs_test.go
  build/pluginctl/main.go
  build/setup.mk
  go.mod
  go.sum
  plugin.go
  plugin.json
  server/command.go
  server/plugin.go
  server/telemetry.go
  webapp/src/action_types/index.js
  webapp/src/actions/index.js
  webapp/src/components/link_tooltip/index.js
  webapp/src/components/rhs_sidebar/index.js
  webapp/src/components/sidebar_buttons/index.js
  webapp/src/components/user_attribute/index.js
  webapp/src/index.js
  webapp/src/manifest.js
  webapp/src/manifest.test.tsx
  webapp/src/selectors/index.js
  webapp/src/websocket/index.js
Labels: 2: Dev Review

#433 [MM-99] Added a note to create subscription for "pipeline" event after running a pipeline
  server/command.go
Labels: 3: QA Review

#453 Added check for the 'show' prop before making API request for the link tooltip.
  webapp/src/components/link_tooltip/link_tooltip.jsx
Labels: 2: Dev Review

#458 [MM-452] Upgrade "go-gitlab" package from 0.55 -> 0.97
  go.mod
  go.sum
  server/gitlab/api.go
  server/webhook/merge_request.go
  server/webhook/webhook.go
Labels: 4: Reviews Complete

#460 Release bump 1.8.1
  README.md
  plugin.json
  server/api.go
  server/command.go
  server/command_test.go
  server/configuration_test.go
  server/flow.go
  server/gitlab/api.go
  server/gitlab/gitlab.go
  server/gitlab/mocks/mock_gitlab.go
  server/mocks/mock_gitlab.go
  server/plugin.go
  server/webhook/merge_request.go
  server/webhook/merge_request_fixture_test.go
  server/webhook/merge_request_test.go
  server/webhook/note.go
  webapp/src/actions/index.js
  webapp/src/components/rhs_sidebar/index.js
  webapp/src/components/rhs_sidebar/rhs_sidebar.jsx
  webapp/src/components/sidebar_buttons/button_icons.tsx
  webapp/src/components/sidebar_buttons/index.js
  webapp/src/components/sidebar_buttons/sidebar_buttons.jsx
  webapp/src/components/sidebar_right/index.tsx
  webapp/src/constants/index.js
  webapp/src/hooks/index.ts
  webapp/src/index.js
  webapp/src/selectors/index.js
  webapp/src/utils/user_agent.js
Labels: 4: Reviews Complete
