Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2024-07, with the labels that each got.

#468 [MM-326] Fix issue of gitlab sidebar icons visible when user is not connected
  webapp/src/components/sidebar_header/index.js
  webapp/src/components/sidebar_header/sidebar_header.jsx
Labels: 2: Dev Review, 3: QA Review

#492 Bump css-loader version from 4.3.0 to 6.11.0
  webapp/package-lock.json
  webapp/package.json
  webapp/tsconfig.json
Labels: 2: Dev Review

#505 Update CODEOWNERS
  CODEOWNERS
Labels: 4: Reviews Complete
