Repository mattermost/mattermost-plugin-gitlab, pull requests merged in 2024-11, with the labels that each got.

#533 Fixing failing CI by updating golang-ci lint version
  Makefile
Labels: 2: Dev Review

#514 Optimized code to decrease the number of API calls to get label details
  build/custom.mk
  go.mod
  go.sum
  server/command_test.go
  server/gitlab/api.go
  server/gitlab/gitlab.go
  server/gitlab/mocks/mock_gitlab.go
  server/mocks/mock_gitlab.go
  webapp/src/components/link_tooltip/index.tsx
  webapp/src/components/sidebar_right/gitlab_items.tsx
  webapp/src/types/gitlab_items.ts
Labels: 3: QA Review

#524 [MM-232]: Fixed the issue of same message being received while creating and deleting tags
  server/webhook/tag.go
Labels: 4: Reviews Complete

#510 [GH-461] Handle case of very long title and label in RHS
  webapp/src/components/sidebar_right/gitlab_items.tsx
  webapp/src/selectors/index.js
Labels: 4: Reviews Complete

#512 [MM-454] Fix Invalid message while creating subscription for a project with no access to create webhook
  server/command.go
  server/command_test.go
Labels: 2: Dev Review, 3: QA Review

#511 [GH-449] Fix DM notification messages
  server/webhook/merge_request.go
  server/webhook/merge_request_test.go
Labels: 4: Reviews Complete

#519 [MM-516]: Fixed the plugin crashing on running subscription add command without arguments
  server/command.go
Labels: 4: Reviews Complete

#518 [MM-517]: Fixed the issue 'Unable to subscribe to groups or subgroups
  server/command.go
Labels: 4: Reviews Complete
